test

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -11,41 +11,43 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      - name: Set up Python 🐍
-        uses: actions/setup-python@v1
-        with:
-          python-version: 3.9
+      - name: test
+        run: env
+      # - name: Set up Python 🐍
+      #   uses: actions/setup-python@v1
+      #   with:
+      #     python-version: 3.9
 
-      - name: Install python dependencies
-        run: pip install pre-commit data-product-definition-tooling
+      # - name: Install python dependencies
+      #   run: pip install pre-commit data-product-definition-tooling
 
-      - name: Generate definitions
-        run: converter src DataProducts
+      # - name: Generate definitions
+      #   run: converter src DataProducts
 
-      - name: Commit and push
-        run: |
-          git status
+      # - name: Commit and push
+      #   run: |
+      #     git status
 
-          if [[ -z $(git status -s) ]]; then
-            echo "No changes detected"
-          else
-            set -x
-            git config --local user.name "${BOT_NAME}"
-            git config --local user.email "${BOT_EMAIL}"
+      #     if [[ -z $(git status -s) ]]; then
+      #       echo "No changes detected"
+      #     else
+      #       set -x
+      #       git config --local user.name "${BOT_NAME}"
+      #       git config --local user.email "${BOT_EMAIL}"
 
-            git add .
-            # format files if necessary
-            pre-commit run --all-files || echo
+      #       git add .
+      #       # format files if necessary
+      #       pre-commit run --all-files || echo
 
-            git add .
-            # run validation one more time. this time exit on error
-            pre-commit run --all-files
+      #       git add .
+      #       # run validation one more time. this time exit on error
+      #       pre-commit run --all-files
 
-            git commit -m "Convert definitions" -a
-            git push https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:${BRANCH}
-          fi
-        env:
-          TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          BRANCH: ${{ github.ref }}
-          BOT_NAME: github-actions[bot]
-          BOT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
+      #       git commit -m "Convert definitions" -a
+      #       git push https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:${BRANCH}
+      #     fi
+      #   env:
+      #     TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #     BRANCH: ${{ github.ref }}
+      #     BOT_NAME: github-actions[bot]
+      #     BOT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
